# Generated by Django 6.0 on 2026-01-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
