# Generated by Django 6.0 on 2026-01-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_classroom_class_teacher_classroom_total_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile/'),
        ),
    ]
