# Generated by Django 6.0 on 2026-01-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='student_profiles.default.png', null=True, upload_to='student_profiles/'),
        ),
    ]
