# Generated by Django 6.0 on 2026-01-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_student_class_name_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
